### ISSUE TITLE
Request for binary (apk)

### ISSUE THREAD

**Issue by AzmuthForger** [JahidHasanCO/NetworkUsage#5]
Hey, I like this app and its feature but sadly I can't complie it can you do that and push an apk file for it ??
Thanks

**Comment by JahidHasanCO** [comment]
Hi @AzmuthForger,
Thanks for your request. This App is demo APK for testing this Library. Here is binary file. 
https://github.com/JahidHasanCO/NetworkUsage/blob/master/signed-keys/app-release.apk
